version: '3.8'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: 1234

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:9000
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./ngnix/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
volumes:
  wordpress_data:
                driver: local
                driver_opts:
                  type: none
                  o: bind
                  device: /home/esekouni/rr/wordpress
  db_data:
          driver: local
          driver_opts:
            type: none
            o: bind
            device: /home/esekouni/rr/database
